### ISSUE TITLE
Error while running 

### ISSUE THREAD

**Issue by RoshaanTariqOfficial** [EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi#11]
RuntimeError: Encountered unresolved custom op: AddV2.Node number 9 (AddV2) failed to prepare.

@EdjeElectronics can u plz help me!

**Comment by EdjeElectronics** [comment]
Hi @RoshaanTariqOfficial , can you tell me which step you got this error on?

**Comment by RoshaanTariqOfficial** [comment]
python TFLite_detection_image.py --modeldir=TFLite_model

**Comment by uchihaltachi** [comment]
how do you solve the problem? I encounter the same problem
