### ISSUE TITLE
PiCamera V1 for Object Detection

### ISSUE THREAD

**Issue by gauti-22** [EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi#117]
I have a question regarding the webcam camera.

Can objection detection be done using Raspberry Pi HD camera V1 ? It can be used as a webcam but I am getting an issue while using for object detection.

Please help!!

**Comment by EdjeElectronics** [comment]
Sorry, I'm not sure what the problem is. I'm closing this issue. If you're still having trouble, please re-open it and copy+paste the specifc error message you're getting when using PiCamera V1.
