### ISSUE TITLE
No Bounding box

### ISSUE THREAD

**Issue by Kondwani23** [EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi#119]
My code is running perfectly without any errors the issue is that no bounding box is drawn

**Comment by EdjeElectronics** [comment]
Try running the program with a 1% confidence threshold using the `--threshhold` argument, and see if any bounding boxes show up. If they do, that just means your model isn't accurate enough to find objects at a high confidence.

```
python TFLite_detection_webcam.py --modeldir=Sample_TFLite_model --threshold=0.01
```

**Comment by Kondwani23** [comment]
Thank you for your response, how can I run it on android?
