### ISSUE TITLE
Quantization challenges

### ISSUE THREAD

**Issue by babydudgeon** [EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi#12]
-Tensorflow 1.14

I reached some challenges when training and exporting different quantized models with your tutorial. I initially took a MobilNet-V2-Quantized model and trained it on multiple classes of moths. Upon training the outputted information reads as below. That is was skipping some quantization.

![TesnorflowGithubIsue](https://user-images.githubusercontent.com/57721562/68782281-c00b0080-05fe-11ea-8ad4-9bff83d8d7fe.JPG)

I ignored this warning and went on through the training process. Gained a loss consistently under 2 and saved a packet with a 1.58 loss. After going through the process of building the build_tenorflow conda environment I attempted to transform the model to a TF_Lite model with the output below

![GITHUBASDF](https://user-images.githubusercontent.com/57721562/68783110-16c50a00-0600-11ea-9e96-60a0344db412.JPG)

with an unsupported data type for the quantization holder, the model would transform to an empty model with 0kb as below.

![GITHUB ISSUES](https://user-images.githubusercontent.com/57721562/68783217-407e3100-0600-11ea-923a-2fe8a3ade8b9.JPG)

I also found out that the model did not have an identifier when attempting to build this model as below. 

![githubissue_2](https://user-images.githubusercontent.com/57721562/68783277-57bd1e80-0600-11ea-848b-84aabca1b72b.JPG)

I attempted the same process with the facessd_mobilenet_v2_quanitzed model and got the same output. Where do you think the error in this process is?

THANKS EVAN!!!!!!!

**Comment by Petros626** [comment]
I hope my assumptions are correct:

Models **with** the addition **quantized** in the name, do not need to be quantized, **they already are.**
Models **without** the addition **can be quantized** with post/aware-quantization.
**TensorFlow 2** forces us until now to post-quantize any model, because the authors didn't offer quantized trained models (weights+activation layers) like `ssd_mobilenet_v2_QUANTIZED`
