### ISSUE TITLE
Tflite converted  from Yolov5

### ISSUE THREAD

**Issue by iliasLab** [EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi#138]
Hello everybody. I'd like to use my yolov5n custom weights on tensorflow lite, but using their converted version (e.g yolov5n-f16.ftlite) always leads to the same bounding box index error.
Could you help me please use them?

**Comment by iliasLab** [comment]
@EdjeElectronics could you please answer me, so I can find out if I have to change training model to export tflite

**Comment by EdjeElectronics** [comment]
Hi @iliasLab , I haven't tried using YOLOv5 with TensorFlow Lite, and I'm not sure if it will work. Sorry I can't be more help.
