### ISSUE TITLE
rumtime error in colab

### ISSUE THREAD

**Issue by rssurya19** [EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi#143]
can you run the labeled dataset i have created bro. has i am able not able run the time .
it would be helpful for me as well as useful for you in experimentation

[https://drive.google.com/drive/folders/1Sjg9Pv5wblkNAdv2sj7DIwW4XJOrvrRW?usp=sharing]
if possible other wise reply with "no"

**Comment by EdjeElectronics** [comment]
No. Sorry, I don't have time ☹️. Hope you can get it figured out! You can also pay $10USD (not sure what it is in other countries) for a month of [Google Colab Pro](https://colab.research.google.com/signup), which increases the session runtime.
