### ISSUE TITLE
hash update...

### ISSUE THREAD

**Issue by Yang-Seong-Eun** [EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi#15]
I execute this line bash get_pi_requirements.sh
but error like this -> "THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them."

**Comment by EdjeElectronics** [comment]
Hi, this just means that the files were corrupted somehow while being downloaded. Try re-running the `bash get_pi_requirements.sh` a couple times until you stop getting the error.

Please re-open this issue if that doesn't solve the problem!
