### ISSUE TITLE
Picamera v3 and libcamera

### ISSUE THREAD

**Issue by diogodh** [EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi#158]
The new picamera v3 doesn't work with legacy anyome and needs libcamera. This way, the script needs to be modified to work with libcamera.
The error it outputs is
` frame = frame1.copy()
AttributeError: 'NoneType' object has no attribute 'copy'`

If anyone can help porting the script to use libcam would be awesome

**Comment by Petros626** [comment]
I only know PiCamera2 (Python). You mean a camera model or software? Either you have wrong ordered code commands or your camera is really not detected.

**Comment by diogodh** [comment]
Sorry for don't explain me correctly. I mean the Raspberry Camera V3 (hardware) is showing an error. Nothing related to the library picamera2.

**Comment by diogodh** [comment]
Not solved but i need to frame the issue better to i can explain myself
better
I can use it on my windows laptop perfectly but in my Raspberry pi with the
new raspberry camera V3 i can't.

I am not sure if it is related with the fact that with raspberry camera V3,
the old legacy camera libraries were depreciated.

**Comment by Petros626** [comment]
this issue is better placed here https://github.com/orgs/raspberrypi/repositories
