### ISSUE TITLE
ModuleNotFoundError: No module named 'object_detection'

### ISSUE THREAD

**Issue by SpiderElectronics** [EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi#171]
Hello Evan:
!pip install pyyaml==5.3 installation error showing error: subprocess-exited-with-error

Displayed when the next module is run:

# Run Model Bulider Test file, just to verify everything's working properly
!python /content/models/research/object_detection/builders/model_builder_tf2_test.py

Traceback (most recent call last):
  File "/content/models/research/object_detection/builders/model_builder_tf2_test.py", line 24, in <module>
    from object_detection.builders import model_builder
ModuleNotFoundError: No module named 'object_detection'

**Comment by 5amleach** [comment]
Hi, yes I am experiencing the exact same issue.

**Comment by Jimbwlah** [comment]
I'm getting the same issue today - this colab was working last week

**Comment by EdjeElectronics** [comment]
Thanks all! I'll look into it.

**Comment by stenglx** [comment]
https://github.com/tensorflow/models/issues/11085#issuecomment-1716889016

Solves the issue for me

**Comment by 5amleach** [comment]
> [tensorflow/models#11085 (comment)](https://github.com/tensorflow/models/issues/11085#issuecomment-1716889016)
> 
> Solves the issue for me

thank you that solved it for me too

**Comment by Jimbwlah** [comment]
> [tensorflow/models#11085 (comment)](https://github.com/tensorflow/models/issues/11085#issuecomment-1716889016)
> 
> Solves the issue for me

Thank you, that also solved it for me!

**Comment by EdjeElectronics** [comment]
Thanks @stenglx , you rock! I just updated the Colab to implement that change. I tested the full notebook and everything worked. Please re-open this issue if the error still crops up.

**Comment by skupperr** [comment]
This issue, "ModuleNotFoundError: No module named 'object_detection'", is happening again. 😢
