### ISSUE TITLE
Using the Coral USB Accelerator needs additional code

### ISSUE THREAD

**Issue by Maatss** [EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi#20]
I get the following error when attempting to use the Coral USB Accelerator
```
python3 TFLite_detection_webcam.py --modeldir=Sample_TFLite_model/ --labels=labelmap.txt --graph=detect_edgetpu.tflite
INFO: Initialized TensorFlow Lite runtime.
Traceback (most recent call last):
  File "TFLite_detection_webcam.py", line 120, in <module>
    interpreter.allocate_tensors()
  File "/home/pi/Downloads/tflite1/tflite1-env/lib/python3.7/site-packages/tensorflow_core/lite/python/interpreter.py", line 244, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "/home/pi/Downloads/tflite1/tflite1-env/lib/python3.7/site-packages/tensorflow_core/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 106, in AllocateTensors
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: Encountered unresolved custom op: edgetpu-custom-op.Node number 0 (edgetpu-custom-op) failed to prepare.
```
Found a fix by doing the following [https://stackoverflow.com/questions/58458967/tf-converter-all-mapped-while-still-encounter-unresolved-custom-op](https://stackoverflow.com/questions/58458967/tf-converter-all-mapped-while-still-encounter-unresolved-custom-op)

Solution:

- [1/2] Import load_delegate

/.../
if pkg is None:
    from tflite_runtime.interpreter import Interpreter
   **from tflite_runtime.interpreter import load_delegate**
else:
    from tensorflow.lite.python.interpreter import Interpreter
    **from tensorflow.lite.python.interpreter import load_delegate**
/.../

- [2/2] Calling the delegate

/.../
#Load the Tensorflow Lite model and get details
**#** interpreter = Interpreter(model_path=PATH_TO_CKPT)
**interpreter = Interpreter(model_path=PATH_TO_CKPT, experimental_delegates=[load_delegate("libedgetpu.so.1.0")])**
/.../

Other info:
I use a newly installed Raspian Buster on a Raspberry pi 4B - 4GB RAM

**Comment by EdjeElectronics** [comment]
Thanks for the input! I have been intending to add this to the code, but have been too busy the past couple weeks to continue working on this guide. I will be adding USB Accelerator functionality in the next two weeks.
