### ISSUE TITLE
import cv2 ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by hathemi** [EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi#21]
(tensorflow-build) C:\tensorflow-build>python TFLite_detection_webcam.py --modeldir=C:\tensorflow\models\research\object_detection\coco_ssd_mobilenet_v1_1.0_quant_2018_06_29
Traceback (most recent call last):
  File "TFLite_detection_webcam.py", line 19, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

i have installed tensorflow V1.13.2, but i always got this error !!
how can i fix it ?

**Comment by redfoo22** [comment]
I'm getting same error "No module named 'cv2" . I'm in the virtual env and I went to install opencv-python and i already have it installed. perhaps cv2 is the incorrect name for the import statement?

**Comment by jasalazar** [comment]
I am having the same error on an AIY Google Vision Kit, and I cannot even install opencv-python on my Raspberry Pi Zero WH.

**Comment by lilithebowman** [comment]
To get opencv to install, the name has changed to python3-opencv

**Comment by lilithebowman** [comment]
This was my fix for the install script
![image](https://user-images.githubusercontent.com/1637212/102233795-a2256480-3ebe-11eb-90be-b0ba9268cfd6.png)
