### ISSUE TITLE
ERROR: Config value opt is not defined in any .rc file

### ISSUE THREAD

**Issue by hamzatanweer** [EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi#24]
tensorflow-build) C:\tensorflow-build>bazel run -config=opt tensorflow/lite/toco:toco - --input_file=%OUTPUT_DIR%/tflite_graph.pb --output_file=%OUTPUT_DIR%/detect.tflite --input_shapes=1,300,300,3 --input_arrays=normalized_input_image_tensor --output_arrays=TFLite_Detection_PostProcess,TFLite_Detection_PostProcess:1,TFLite_Detection_PostProcess:2,TFLite_Detection_PostProcess:3 --inference_type=QUANTIZED_UINT8 --mean_values=128 --std_values=128 --change_concat_input_ranges=false --allow_custom_ops

Got this error please help asap!

INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Options provided by the client:
  Inherited 'build' options: --python_path=C:/Users/hamza/Anaconda3/envs/tensorflow-build/python.exe
ERROR: Config value opt is not defined in any .rc file

**Comment by alexatinvert** [comment]
For me the solution was to execute the command from the tensorflow floder, i.e. /home/username/tensorflow/tensorflow/

This folder contains workspace.bzl, which I believe contains the config values
