### ISSUE TITLE
ERROR conda.core.link:_execute(700): An error occurred while installing package 'defaults::m2-base-1.0.0-3'.

### ISSUE THREAD

**Issue by saqibshakeel035** [EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi#27]
I am trying to follow your [this tutorial ](https://github.com/EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi#step-3-use-toco-to-create-optimzed-tensorflow-lite-model) and I am stuck at **Step 2d. Download Bazel and Python package dependencies**
Getting same error while installing different bazel versions.
My TensorFlow version is 1.15
I am running Anaconda prompt as administrator privileges:
Following is my error:
`(tensorflow-build) C:\Windows\system32>conda install -c conda-forge bazel=0.24.1
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\Saqib\Anaconda3\envs\tensorflow-build

  added / updated specs:
    - bazel=0.24.1

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bazel-0.24.1               |       he3c9ec2_0        58.0 MB
    ca-certificates-2019.11.28 |       hecc5488_0         182 KB  conda-forge
    certifi-2019.11.28         |           py37_0         148 KB  conda-forge
    openssl-1.1.1d             |       hfa6e2cd_0         4.7 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        63.0 MB`
The following NEW packages will be INSTALLED:

 `The following NEW packages will be INSTALLED:

  bazel              pkgs/main/win-64::bazel-0.24.1-he3c9ec2_0
  m2-base            pkgs/msys2/win-64::m2-base-1.0.0-3
  m2-bash            pkgs/msys2/win-64::m2-bash-4.3.042-5
  m2-bash-completion pkgs/msys2/win-64::m2-bash-completion-2.3-2
  m2-catgets         pkgs/msys2/win-64::m2-catgets-1.1-3
  m2-coreutils       pkgs/msys2/win-64::m2-coreutils-8.25-102
  m2-dash            pkgs/msys2/win-64::m2-dash-0.5.8-2
  m2-diffutils       pkgs/msys2/win-64::m2-diffutils-3.3-4
  m2-file            pkgs/msys2/win-64::m2-file-5.25-2
  m2-filesystem      pkgs/msys2/win-64::m2-filesystem-2016.04-4
  m2-findutils       pkgs/msys2/win-64::m2-findutils-4.6.0-2
  m2-gawk            pkgs/msys2/win-64::m2-gawk-4.1.3-2
  m2-gcc-libs        pkgs/msys2/win-64::m2-gcc-libs-5.3.0-4
  m2-gettext         pkgs/msys2/win-64::m2-gettext-0.19.7-4
  m2-gmp             pkgs/msys2/win-64::m2-gmp-6.1.0-3
  m2-grep            pkgs/msys2/win-64::m2-grep-2.22-4
  m2-gzip            pkgs/msys2/win-64::m2-gzip-1.7-2
  m2-inetutils       pkgs/msys2/win-64::m2-inetutils-1.9.2-2
  m2-info            pkgs/msys2/win-64::m2-info-6.0-2
  m2-less            pkgs/msys2/win-64::m2-less-481-2
  m2-libasprintf     pkgs/msys2/win-64::m2-libasprintf-0.19.7-4
  m2-libbz2          pkgs/msys2/win-64::m2-libbz2-1.0.6-3
  m2-libcatgets      pkgs/msys2/win-64::m2-libcatgets-1.1-3
  m2-libcrypt        pkgs/msys2/win-64::m2-libcrypt-1.3-2
  m2-libgettextpo    pkgs/msys2/win-64::m2-libgettextpo-0.19.7-4
  m2-libiconv        pkgs/msys2/win-64::m2-libiconv-1.14-3
  m2-libintl         pkgs/msys2/win-64::m2-libintl-0.19.7-4
  m2-liblzma         pkgs/msys2/win-64::m2-liblzma-5.2.2-2
  m2-libpcre         pkgs/msys2/win-64::m2-libpcre-8.38-2
  m2-libreadline     pkgs/msys2/win-64::m2-libreadline-6.3.008-8
  m2-libutil-linux   pkgs/msys2/win-64::m2-libutil-linux-2.26.2-2
  m2-libxml2         pkgs/msys2/win-64::m2-libxml2-2.9.2-3
  m2-make            pkgs/msys2/win-64::m2-make-4.1-5
  m2-mintty          pkgs/msys2/win-64::m2-mintty-1!2.2.3-2
  m2-mpfr            pkgs/msys2/win-64::m2-mpfr-3.1.4-2
  m2-msys2-launcher~ pkgs/msys2/win-64::m2-msys2-launcher-git-0.3.28.860c495-2
  m2-msys2-runtime   pkgs/msys2/win-64::m2-msys2-runtime-2.5.0.17080.65c939c-3
  m2-ncurses         pkgs/msys2/win-64::m2-ncurses-6.0.20160220-2
  m2-sed             pkgs/msys2/win-64::m2-sed-4.2.2-3
  m2-tar             pkgs/msys2/win-64::m2-tar-1.28-4
  m2-tftp-hpa        pkgs/msys2/win-64::m2-tftp-hpa-5.2-2
  m2-time            pkgs/msys2/win-64::m2-time-1.7-2
  m2-ttyrec          pkgs/msys2/win-64::m2-ttyrec-1.0.8-2
  m2-tzcode          pkgs/msys2/win-64::m2-tzcode-2015.e-2
  m2-unzip           pkgs/msys2/win-64::m2-unzip-6.0-3
  m2-util-linux      pkgs/msys2/win-64::m2-util-linux-2.26.2-2
  m2-which           pkgs/msys2/win-64::m2-which-2.21-3
  m2-zip             pkgs/msys2/win-64::m2-zip-3.0-2
  m2-zlib            pkgs/msys2/win-64::m2-zlib-1.2.8-4
  msys2-conda-epoch  pkgs/msys2/win-64::msys2-conda-epoch-20160418-1
  openjdk            conda-forge/win-64::openjdk-11.0.1-1017
  posix              pkgs/msys2/win-64::posix-1.0.0-2
  vs2013_runtime     pkgs/main/win-64::vs2013_runtime-12.0.21005-1

The following packages will be UPDATED:

  ca-certificates    anaconda::ca-certificates-2019.11.27-0 --> conda-forge::ca-certificates-2019.11.28-hecc5488_0

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi                                          anaconda --> conda-forge
  openssl                anaconda::openssl-1.1.1-he774522_0 --> conda-forge::openssl-1.1.1d-hfa6e2cd_0

Proceed ([y]/n)? y
`
The following packages will be UPDATED:

  ca-certificates    anaconda::ca-certificates-2019.11.27-0 --> conda-forge::ca-certificates-2019.11.28-hecc5488_0

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi                                          anaconda --> conda-forge
  openssl                anaconda::openssl-1.1.1-he774522_0 --> conda-forge::openssl-1.1.1d-hfa6e2cd_0

Proceed ([y]/n)? y

Downloading and Extracting Packages
bazel-0.24.1         | 58.0 MB   | ############################################################################################################################ | 100%
certifi-2019.11.28   | 148 KB    | ############################################################################################################################ | 100%
ca-certificates-2019 | 182 KB    | ############################################################################################################################ | 100%
openssl-1.1.1d       | 4.7 MB    | ############################################################################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'defaults::m2-base-1.0.0-3'.
Rolling back transaction: done

LinkError: post-link script failed for package defaults::m2-base-1.0.0-3
location of failed script: C:\Users\Saqib\Anaconda3\envs\tensorflow-build\Scripts\.m2-base-post-link.bat
==> script messages <==
<None>
==> script output <==
stdout:
stderr: 'chcp' is not recognized as an internal or external command,
operable program or batch file.
'chcp' is not recognized as an internal or external command,
operable program or batch file.
'chcp' is not recognized as an internal or external command,
operable program or batch file.

return code: 1

()

**Comment by daye-oa** [comment]
have you bee able to get a solution to this ?
