### ISSUE TITLE
What will happen if we build the tensorflow from source with the 'tensorflow1'?

### ISSUE THREAD

**Issue by HaFred** [EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi#3]
I am just curious, did you try building tensorflow from source with 'tensorflow1'?

**Comment by EdjeElectronics** [comment]
No, I decided to keep them separate. It would probably work fine, just make sure you build the GPU version if you're going to use the "tensorflow1" environment for training.
