### ISSUE TITLE
Error when running final step

### ISSUE THREAD

**Issue by masamune-prog** [EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi#41]
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/tflite1/Sample_TFLite_mode/labelmap.txt'
Whats wrong? Please help

**Comment by EdjeElectronics** [comment]
Looks like you typed the "Sample_TFLite_model" portion wrong.
