### ISSUE TITLE
How to control FPS ?

### ISSUE THREAD

**Issue by TAThink** [EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi#49]
Hello.
I builded Tensorflow Lite with Raspberry Pi 3 B +.
FPS is below 0.9

Is there anything that can be improved?

thank you :)

**Comment by EdjeElectronics** [comment]
You can run it with a lower resolution by using the --resolution argument. This will help it run a little faster. For example, to run it at a 640x480 resolution, use:

```
python3 TFLite_detection_webcam.py --modeldir=Sample_TFLite_model --resolution=640x480
```

Also, make sure to close all other programs before running it!
