### ISSUE TITLE
How to use multiple cores to speed up the inference time?

### ISSUE THREAD

**Issue by zanazakaryaie** [EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi#51]
Hello. Let me first thank you for your tutorial. 

I could successfully run the model on a video and see the detections. BUT, when I do `htop`, I can see that only one core is used! How can I force the TensorFlow to use the other cores too?

**Comment by EdjeElectronics** [comment]
I don't know! Maybe someone else can suggest a method.

**Comment by zanazakaryaie** [comment]
Did you experience the same issue?

**Comment by kevin5k** [comment]
@zanazakaryaie , can you share more information on which pi are you running your model on? Any screenshots to share(if possible)?

**Comment by HanYangZhao** [comment]
Maybe you could try this pre-buillt binary of tflite which supports multi-thread
 https://github.com/PINTO0309/TensorflowLite-bin
