### ISSUE TITLE
IP and not a USB cam

### ISSUE THREAD

**Issue by hamelsveld** [EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi#65]
Hi,

Do you also have some example code by using a IP cam? and not a USB or PI CAM?

Tnx

**Comment by HanYangZhao** [comment]
Did you try with TFLite_detection_stream.py?

**Comment by EdjeElectronics** [comment]
Please see https://github.com/EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi#video-stream for how to use this with an IP camera :smile:
