### ISSUE TITLE
Cannot run the TFLite_detection_stream.py code.

### ISSUE THREAD

**Issue by Dasinator21** [EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi#77]
python TFLite_detection_stream.py --modeldir=TFLite_model --streamurl="http://ipaddress:port/stream/video.mjpeg" 

the output I get:
[tcp @ 0xf7ad40] Port missing in uri
Traceback (most recent call last):
  File "TFLite_detection_stream.py", line 174, in <module>
    frame = frame1.copy()
AttributeError: 'NoneType' object has no attribute 'copy'

How can I run this code!!!

**Comment by uyesad** [comment]
did you solve the problem

**Comment by nozma-knows** [comment]
I'm having the same issue

**Comment by basnugroho** [comment]
i'm having the same issue

**Comment by busqui04** [comment]
same issue here. Did you find how to fix it?

**Comment by EdjeElectronics** [comment]
Please read the [FAQ](https://github.com/EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi/blob/master/deploy_guides/Raspberry_Pi_Guide.md#1-typeerror-int-argument-must-be-a-string-a-bytes-like-object-or-a-number-not-nonetype). It's most likely a problem with your camera.
