### ISSUE TITLE
Protocol message SsdFeatureExtractor has no field fpn.

### ISSUE THREAD

**Issue by sergio-vg** [EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi#94]
Hello, im getting "ValueError: Protocol message SsdFeatureExtractor has no field fpn." while runing export_tflite_ssd_graph.py

**Comment by sergio-vg** [comment]
![Imagen1](https://user-images.githubusercontent.com/76799471/103391235-f1ce7780-4add-11eb-856e-6862231b310d.png)

**Comment by EdjeElectronics** [comment]
What type of model are you training? If it isn't an SSD-MobileNet model, it isn't supported by TFLite. I think you're using a model that isn't supported.
